name: test

on:
  workflow_dispatch:
  pull_request:

jobs:
  test_linux:
    name: "test on linux"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python_version }}"
          cache: "pip"
      - name: setup
        run: |
          script/setup --dev
      - name: test
        run: |
          script/lint
          script/test
